# coding: utf-8
from sqlalchemy import *
from sqlalchemy.dialects.mssql import BIT
from sqlalchemy.dialects.mysql.types import _IntegerType, _StringType
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()


class GlobalOrderOperate(Base):
    __tablename__ = 'global_order_operate'
    __table_args__ = (
        Index('ix_pc', 'processcenter_id', 'request_status', 'operate_time'),
    )

    id = Column(_IntegerType(20), primary_key=True)
    processcenter_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    global_order_code = Column(_StringType(50), nullable=False, index=True, server_default="''")
    operate_time = Column(DateTime, nullable=False, server_default='CURRENT_TIMESTAMP')
    operate_user_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    operate_user_name = Column(_StringType(50), nullable=False, server_default="''")
    operate_platform = Column(_IntegerType(4), nullable=False, server_default="'0'")
    operate_guid = Column(_StringType(50), nullable=False, server_default="''")
    operate_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    request_status = Column(_IntegerType(4), nullable=False, index=True, server_default="'0'")
    request_body = Column(_StringType(5000), nullable=False, server_default="''")
    exp_message = Column(_StringType(500), nullable=False, server_default="''")
    lock_version = Column(_IntegerType(11), nullable=False, server_default="'0'")
    extend_body = Column(_IntegerType(4), nullable=False, server_default="'0'")
    last_execute_time = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")


class OdsPckAttached(Base):
    __tablename__ = 'ods_pck_attached'

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    order_id = Column(_StringType(20), nullable=False, server_default="''")
    is_repeat_send = Column(BIT(1))
    is_replenishment = Column(BIT(1))
    is_split = Column(BIT(1))
    setting = Column(_StringType(50))
    original_currency = Column(_StringType(10))
    original_amount = Column(DECIMAL(18, 3))
    original_ship_fee = Column(DECIMAL(18, 3))
    original_total_fee = Column(DECIMAL(18, 3))
    platform_id = Column(_StringType(10))
    platform_name = Column(_StringType(30), nullable=False, server_default="''")
    store_id = Column(_StringType(20))
    store_name = Column(_StringType(50), nullable=False, server_default="''")
    logistics_account = Column(_StringType(5))
    sales_user_id = Column(_IntegerType(11), server_default="'0'")
    product_manager_id = Column(_IntegerType(11), server_default="'0'")
    product_manager_name = Column(_StringType(50))
    sales_user_name = Column(_StringType(50))
    order_track_type = Column(_IntegerType(11))
    region = Column(_StringType(50))
    area = Column(_StringType(50))
    weight_level = Column(_StringType(5))
    is_multi_storage_delivery = Column(BIT(1))
    pack_require_id = Column(_StringType(4000))
    deficit_price = Column(DECIMAL(18, 3))
    lights_goods_freight = Column(DECIMAL(18, 3))
    loss_condition = Column(_StringType(100))
    jettison_condition = Column(_StringType(100))
    is_cost_control = Column(_IntegerType(20))
    max_feight = Column(DECIMAL(18, 3))
    package_service_fee = Column(DECIMAL(18, 3))
    package_material_fee = Column(DECIMAL(18, 3))
    create_date = Column(DateTime, nullable=False, index=True)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, server_default="'1970-01-02 00:00:00'")
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    lable_types = Column(_StringType(100), nullable=False, server_default="''")
    requirement_types = Column(_StringType(2000), nullable=False, server_default="''")
    jump_abroad_warehouse_status = Column(_IntegerType(4), nullable=False, server_default="'0'")
    stock_store_id = Column(_StringType(20), nullable=False, server_default="''")
    customer_order_type = Column(_StringType(20), nullable=False, server_default="''")
    ioss_number = Column(_StringType(500), nullable=False, server_default="''")
    recipient_info_decryption_code = Column(_StringType(255), nullable=False, server_default="''")


class OdsPckDetail(Base):
    __tablename__ = 'ods_pck_detail'

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False)
    order_detail_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    item_id = Column(_StringType(1000), nullable=False, server_default="''")
    item_name = Column(_StringType(800))
    base_product_name = Column(_StringType(255), nullable=False, server_default="''")
    base_packing_specification = Column(_IntegerType(2), nullable=False, server_default="'0'")
    sale_price = Column(DECIMAL(15, 4), server_default="'0.0000'")
    quantity = Column(_IntegerType(11), nullable=False)
    bar_code_id = Column(_StringType(50))
    sku = Column(_StringType(50), nullable=False, index=True)
    poa = Column(_StringType(50), nullable=False, index=True, server_default="''")
    bar_code = Column(_StringType(50), server_default="''")
    length = Column(DECIMAL(9, 2))
    width = Column(DECIMAL(9, 2))
    height = Column(DECIMAL(9, 2))
    goods_spec = Column(_StringType(50))
    goods_attachment_id = Column(_IntegerType(11))
    item_delivery_weight = Column(DECIMAL(12, 3))
    goods_manager_name = Column(_StringType(30))
    sales_user_name = Column(_StringType(30))
    platform_order_id = Column(_StringType(800))
    os_detail_id = Column(_StringType(30))
    transaction_id = Column(DECIMAL(18, 0))
    create_date = Column(DateTime, nullable=False)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default="'1970-01-02 00:00:00'")
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    goods_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    bg_product_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    bg_property_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    adapter_num = Column(_IntegerType(11), nullable=False, server_default="'0'")
    goods_label = Column(_StringType(300), server_default="''")
    category_id_path = Column(_StringType(255), nullable=False, server_default="''")
    category_cn_name_path = Column(_StringType(255), nullable=False, server_default="''")
    platform_category_id = Column(_StringType(255), nullable=False, server_default="''")
    cost_price = Column(DECIMAL(15, 4), server_default="'0.0000'")
    order_detail_info_json = Column(_StringType(2000), nullable=False, server_default="''")


class OdsPckHaikwanDetail(Base):
    __tablename__ = 'ods_pck_haikwan_detail'

    id = Column(_IntegerType(20), primary_key=True, nullable=False)
    package_id = Column(_StringType(20), primary_key=True, nullable=False)
    sku = Column(_StringType(50), nullable=False, index=True, server_default="''")
    cn_name = Column(_StringType(200), nullable=False, server_default="''")
    en_name = Column(_StringType(200), nullable=False, server_default="''")
    quantity = Column(_IntegerType(11), nullable=False)
    producing_area = Column(_StringType(10))
    weight = Column(DECIMAL(9, 3), nullable=False, server_default="'0.000'")
    currency = Column(_StringType(10))
    value = Column(DECIMAL(10, 3), nullable=False, server_default="'0.000'")
    hscode = Column(_StringType(20))
    create_date = Column(DateTime, nullable=False)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default="'1970-01-02 00:00:00'")
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    battery_type = Column(_IntegerType(11), nullable=False, server_default="'0'")


class OdsPckInfo(Base):
    __tablename__ = 'ods_pck_info'
    __table_args__ = (
        Index('idx_indate_isdelete', 'in_ods_date_time', 'is_deleted'),
        Index('idx_delivery_date', 'delivery_date', 'delivery_user')
    )

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    order_id = Column(_StringType(30), nullable=False, index=True, server_default="''")
    process_center_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delivery_type = Column(_StringType(50), nullable=False, server_default="''")
    order_type = Column(_StringType(20))
    detail_type = Column(_IntegerType(11))
    package_type = Column(_IntegerType(11))
    batch_processing_id = Column(_StringType(50), index=True)
    pck_state = Column(_IntegerType(11))
    change_state_time = Column(DateTime)
    in_ods_date_time = Column(DateTime)
    in_wsp_datetime = Column(DateTime)
    in_system_datetime = Column(DateTime)
    freight = Column(DECIMAL(18, 3))
    total_price = Column(DECIMAL(18, 3))
    actual_weight = Column(DECIMAL(9, 3))
    goods_pck_weight = Column(DECIMAL(9, 3), server_default="'0.000'")
    volume_weight = Column(DECIMAL(9, 3), server_default="'0.000'")
    package_length = Column(DECIMAL(9, 2), server_default="'0.00'")
    package_width = Column(DECIMAL(9, 2), server_default="'0.00'")
    package_height = Column(DECIMAL(9, 2), server_default="'0.00'")
    post_id = Column(_StringType(11), index=True)
    post_type_options = Column(_StringType(1000))
    online_psot_type = Column(_StringType(100))
    trace_id = Column(_StringType(80), index=True)
    way_bill_no = Column(_StringType(80))
    delivery_date = Column(DateTime)
    delivery_user_id = Column(_IntegerType(11))
    delivery_user = Column(_StringType(20), index=True)
    receive_name = Column(_StringType(100))
    phone = Column(_StringType(50))
    country_id = Column(_StringType(20), index=True)
    country = Column(_StringType(300))
    county = Column(_StringType(300))
    city = Column(_StringType(300))
    buyer_address1 = Column(_StringType(300))
    buyer_address2 = Column(_StringType(300))
    zip = Column(_StringType(150))
    belonging = Column(_StringType(20))
    belonging_id = Column(_IntegerType(2), nullable=False, server_default="'0'")
    pck_remarks = Column(_StringType(800))
    platform_order_id = Column(_StringType(800))
    master_post_no_jump = Column(_IntegerType(1))
    is_part_delivery = Column(BIT(1))
    is_gift_lack_delivery = Column(BIT(1))
    processing_scheme = Column(_StringType(50))
    processing_scheme_remark = Column(_StringType(1000))
    return_reason_name = Column(_StringType(100))
    return_reason_remark = Column(_StringType(1000))
    ods_site_server = Column(_StringType(50))
    create_date = Column(DateTime, nullable=False, index=True)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    init_pck_volume = Column(DECIMAL(20, 3), nullable=False, server_default="'0.000'")
    address = Column(_StringType(300), nullable=False, server_default="''")
    email = Column(_StringType(150), nullable=False, server_default="''")
    payment_type = Column(_IntegerType(4), nullable=False, server_default="'1'")
    user_trace_id = Column(_StringType(255), nullable=False, server_default="''")
    real_post_id = Column(_StringType(20), nullable=False, server_default="''")
    earliest_delivery_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    deliver_goods_id = Column(_StringType(30), nullable=False, server_default="''")
    order_info_json = Column(_StringType(2000), nullable=False, server_default="''")
    send_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    container_code = Column(_StringType(50), nullable=False, server_default="''")


class PackageInfo(Base):
    __tablename__ = 'package_info'
    __table_args__ = (
        Index('idx_status_outbound_type_pck_state', 'status', 'outbound_type', 'pck_state'),
    )

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    order_id = Column(_StringType(30), nullable=False, index=True, server_default="''")
    overall_code = Column(_StringType(30), nullable=False, server_default="''")
    pck_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    outbound_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    outbound_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    status = Column(_IntegerType(4), nullable=False, index=True, server_default="'0'")
    remark = Column(_StringType(255), nullable=False, server_default="''")
    handle_programme = Column(_IntegerType(4), nullable=False, server_default="'-1'")
    process_prescription = Column(_IntegerType(11), nullable=False, server_default="'0'")
    manager_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    owner_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    priority = Column(_IntegerType(4), nullable=False, server_default="'0'")
    surplus_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    is_stockout = Column(_IntegerType(1), nullable=False, server_default="'0'")
    is_track = Column(_IntegerType(4), nullable=False, server_default="'0'")
    is_since = Column(_IntegerType(1), nullable=False, server_default="'0'")
    process_center_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    platform_id = Column(_StringType(50), nullable=False, server_default="''")
    platform_name = Column(_StringType(50), nullable=False, server_default="''")
    store_id = Column(_StringType(50), nullable=False, server_default="''")
    store_name = Column(_StringType(50), nullable=False, server_default="''")
    delivery_type = Column(_StringType(50), nullable=False, server_default="''")
    order_type = Column(_StringType(20), nullable=False, server_default="''")
    detail_type = Column(_IntegerType(11), nullable=False, server_default="'0'")
    package_type = Column(_IntegerType(11), nullable=False, server_default="'0'")
    batch_processing_id = Column(_StringType(50), nullable=False, index=True, server_default="''")
    pck_state = Column(_IntegerType(11), nullable=False, server_default="'1'")
    change_state_time = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    in_ods_date_time = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    in_wsp_datetime = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    in_system_datetime = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    freight = Column(DECIMAL(18, 3), nullable=False, server_default="'0.000'")
    total_price = Column(DECIMAL(18, 3), nullable=False, server_default="'0.000'")
    actual_weight = Column(DECIMAL(9, 3), nullable=False, server_default="'0.000'")
    goods_pck_weight = Column(DECIMAL(9, 3), nullable=False, server_default="'0.000'")
    volume_weight = Column(DECIMAL(9, 3), nullable=False, server_default="'0.000'")
    package_length = Column(DECIMAL(9, 2), nullable=False, server_default="'0.00'")
    package_width = Column(DECIMAL(9, 2), nullable=False, server_default="'0.00'")
    package_height = Column(DECIMAL(9, 2), nullable=False, server_default="'0.00'")
    post_id = Column(_StringType(11), nullable=False, index=True, server_default="''")
    post_type_options = Column(_StringType(1000), nullable=False, server_default="''")
    online_psot_type = Column(_StringType(100), nullable=False, server_default="''")
    trace_id = Column(_StringType(80), nullable=False, server_default="''")
    way_bill_no = Column(_StringType(80), nullable=False, server_default="''")
    delivery_date = Column(DateTime, nullable=False, index=True, server_default="'1970-01-01 00:00:00'")
    delivery_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delivery_user = Column(_StringType(20), nullable=False, index=True, server_default="''")
    receive_name = Column(_StringType(100), nullable=False, server_default="''")
    phone = Column(_StringType(50), nullable=False, server_default="''")
    country_id = Column(_StringType(20), nullable=False, index=True, server_default="''")
    country = Column(_StringType(300), nullable=False, server_default="''")
    county = Column(_StringType(300), nullable=False, server_default="''")
    city = Column(_StringType(300), nullable=False, server_default="''")
    buyer_address1 = Column(_StringType(300), nullable=False, server_default="''")
    buyer_address2 = Column(_StringType(300), nullable=False, server_default="''")
    zip = Column(_StringType(150), nullable=False, server_default="''")
    belonging = Column(_StringType(20), nullable=False, server_default="''")
    pck_remarks = Column(_StringType(800), nullable=False, server_default="''")
    platform_order_id = Column(_StringType(800), nullable=False, index=True, server_default="''")
    master_post_no_jump = Column(_IntegerType(1), nullable=False, server_default="'0'")
    is_part_delivery = Column(_IntegerType(1), nullable=False, server_default="'0'")
    is_gift_lack_delivery = Column(_IntegerType(1), nullable=False, server_default="'0'")
    processing_scheme = Column(_StringType(50), nullable=False, server_default="''")
    processing_scheme_remark = Column(_StringType(1000), nullable=False, server_default="''")
    return_reason_name = Column(_StringType(100), nullable=False, server_default="''")
    return_reason_remark = Column(_StringType(1000), nullable=False, server_default="''")
    ods_site_server = Column(_StringType(50), nullable=False, server_default="''")
    ship_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    create_date = Column(DateTime, nullable=False, server_default='CURRENT_TIMESTAMP')
    create_user_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    modify_user_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(_IntegerType(1), nullable=False, server_default="'0'")
    delete_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    delete_user_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    create_timestamp = Column(DateTime, nullable=False, server_default='CURRENT_TIMESTAMP')
    target_processcenter_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    exception_type = Column(_IntegerType(4), nullable=False, server_default="'-1'")
    container_code = Column(_StringType(30), nullable=False, server_default="''")
    stock_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    supplier_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    origin_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    lcl_limit_level = Column(_IntegerType(4), nullable=False, server_default="'0'")
    is_charged = Column(_IntegerType(4), nullable=False, server_default="'0'")
    is_liquid = Column(_IntegerType(4), nullable=False, server_default="'0'")
    is_powder_past = Column(_IntegerType(4), nullable=False, server_default="'0'")
    sync_status_ods = Column(_IntegerType(4), nullable=False, server_default="'0'")
    is_full = Column(_IntegerType(4), nullable=False, server_default="'0'")
    store_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    return_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    exception_reason = Column(_IntegerType(4), nullable=False, server_default="'-1'")
    is_drowback = Column(_IntegerType(4), nullable=False, server_default="'0'")
    goods_type = Column(_IntegerType(4), nullable=False, server_default="'-1'")
    owner_name = Column(_StringType(50), nullable=False, server_default="''")
    goods_size = Column(_IntegerType(4), nullable=False, server_default="'0'")
    is_first_order = Column(_IntegerType(11), nullable=False, server_default="'0'")
    sub_ship_type = Column(_IntegerType(4), nullable=False, server_default="'0'")
    bill_mode = Column(_IntegerType(4), nullable=False, server_default="'0'")


class PackageItem(Base):
    __tablename__ = 'package_item'

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    goods_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    goods_name = Column(_StringType(300), nullable=False, server_default="''")
    goods_spec = Column(_StringType(750), nullable=False, server_default="''")
    base_product_code = Column(_StringType(50), nullable=False, server_default="''")
    external_code = Column(_StringType(50), nullable=False, server_default="''")
    produce_id = Column(_StringType(100), nullable=False, server_default="''")
    produce_code = Column(_StringType(100), nullable=False, server_default="''")
    produce_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    valid_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    is_stockout = Column(_IntegerType(1), nullable=False, server_default="'0'")
    manager_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    owner_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    processcenter_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    outbound_strategy = Column(_IntegerType(4), nullable=False, server_default="'0'")
    sale_price = Column(DECIMAL(15, 4), nullable=False, server_default="'0.0000'")
    actual_quantity = Column(_IntegerType(11), nullable=False, server_default="'0'")
    quantity = Column(_IntegerType(11), nullable=False, server_default="'0'")
    length = Column(DECIMAL(9, 2), nullable=False, server_default="'0.00'")
    width = Column(DECIMAL(9, 2), nullable=False, server_default="'0.00'")
    height = Column(DECIMAL(9, 2), nullable=False, server_default="'0.00'")
    goods_attachment_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    item_delivery_weight = Column(DECIMAL(9, 2), nullable=False, server_default="'0.00'")
    goods_manager_name = Column(_StringType(30), nullable=False, server_default="''")
    sales_user_name = Column(_StringType(30), nullable=False, server_default="''")
    platform_order_id = Column(_StringType(800), nullable=False, server_default="''")
    os_detail_id = Column(_StringType(30), nullable=False, server_default="''")
    transaction_id = Column(DECIMAL(18, 0), nullable=False, server_default="'0'")
    create_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    create_user_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    modify_user_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(_IntegerType(1), nullable=False, server_default="'0'")
    delete_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    delete_user_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, server_default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    stockout_quantity = Column(_IntegerType(11), nullable=False, server_default="'0'")
    separate_quantity = Column(_IntegerType(11), nullable=False, server_default="'0'")
    source_order = Column(_StringType(20), nullable=False, server_default="''")
    relation_code = Column(_StringType(30), nullable=False, server_default="''")
    delivery_product_code = Column(_StringType(50), nullable=False, server_default="''")
