# coding: utf-8
from sqlalchemy import *
from sqlalchemy.dialects.mysql.types import _IntegerType, _StringType,BIT
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()


class OdsPckAttached(Base):
    __tablename__ = 'ods_pck_attached'

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    order_id = Column(_StringType(30), nullable=False, index=True, server_default="''")
    is_repeat_send = Column(BIT(1))
    is_replenishment = Column(BIT(1))
    is_split = Column(BIT(1))
    setting = Column(_StringType(50))
    original_currency = Column(_StringType(10))
    original_amount = Column(DECIMAL(18, 3))
    original_ship_fee = Column(DECIMAL(18, 3))
    original_total_fee = Column(DECIMAL(18, 3))
    platform_id = Column(_StringType(10))
    platform_name = Column(_StringType(30), nullable=False, server_default="''")
    store_id = Column(_StringType(20))
    store_name = Column(_StringType(50), nullable=False, server_default="''")
    logistics_account = Column(_StringType(5))
    order_track_type = Column(_IntegerType(11))
    region = Column(_StringType(50))
    area = Column(_StringType(50))
    weight_level = Column(_StringType(5))
    is_multi_storage_delivery = Column(BIT(1))
    pack_require_id = Column(_StringType(200))
    deficit_price = Column(DECIMAL(18, 3))
    lights_goods_freight = Column(DECIMAL(18, 3))
    loss_condition = Column(_StringType(100))
    jettison_condition = Column(_StringType(100))
    is_cost_control = Column(_IntegerType(20))
    max_feight = Column(DECIMAL(18, 3))
    package_service_fee = Column(DECIMAL(18, 3))
    package_material_fee = Column(DECIMAL(18, 3))
    create_date = Column(DateTime, nullable=False, index=True)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default="'1970-01-02 00:00:00'")
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    sales_user_id = Column(_IntegerType(11), server_default="'0'")
    sales_user_name = Column(_StringType(50))
    product_manager_name = Column(_StringType(50))
    product_manager_id = Column(_IntegerType(11), server_default="'0'")
    lable_types = Column(_StringType(100), nullable=False, server_default="''")
    requirement_types = Column(_StringType(2000), nullable=False, server_default="''")
    jump_abroad_warehouse_status = Column(_IntegerType(4), nullable=False, server_default="'0'")
    is_fulfilled = Column(_IntegerType(1), nullable=False, server_default="'0'")
    stock_store_id = Column(_StringType(20), nullable=False, server_default="''")
    mobile_ids = Column(_StringType(255), nullable=False, server_default="''")
    customer_order_type = Column(_StringType(20), nullable=False, server_default="''")
    ioss_number = Column(_StringType(500), nullable=False, server_default="''")


class OdsPckDetail(Base):
    __tablename__ = 'ods_pck_detail'

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    item_id = Column(_StringType(1000), nullable=False, server_default="''")
    item_name = Column(_StringType(800), nullable=False, server_default="''")
    base_product_name = Column(_StringType(255), nullable=False, server_default="''")
    base_packing_specification = Column(_IntegerType(2), nullable=False, server_default="'0'")
    sale_price = Column(DECIMAL(15, 4), server_default="'0.0000'")
    quantity = Column(_IntegerType(11), nullable=False)
    bar_code_id = Column(_StringType(50))
    sku = Column(_StringType(50), nullable=False, index=True)
    poa = Column(_StringType(50), nullable=False, index=True, server_default="''")
    bar_code = Column(_StringType(50), index=True, server_default="''")
    length = Column(DECIMAL(9, 2))
    width = Column(DECIMAL(9, 2))
    height = Column(DECIMAL(9, 2))
    goods_spec = Column(_StringType(750))
    goods_attachment_id = Column(_IntegerType(11))
    item_delivery_weight = Column(DECIMAL(12, 3))
    goods_manager_name = Column(_StringType(30))
    sales_user_name = Column(_StringType(30))
    platform_order_id = Column(_StringType(800))
    os_detail_id = Column(_StringType(30))
    transaction_id = Column(DECIMAL(18, 0))
    create_date = Column(DateTime, nullable=False, index=True)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default="'1970-01-02 00:00:00'")
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    row = Column(_StringType(20), nullable=False, server_default="''")
    rack = Column(_StringType(20), nullable=False, server_default="''")
    position = Column(_StringType(20), nullable=False, server_default="''")
    is_default = Column(_IntegerType(3), nullable=False, server_default="'0'")
    stock_quantity = Column(_IntegerType(11), nullable=False, server_default="'0'")
    order_detail_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    goods_id = Column(_IntegerType(20), nullable=False, server_default="'0'")
    bg_product_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    bg_property_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    adapter_num = Column(_IntegerType(11), nullable=False, server_default="'0'")
    is_get_rack = Column(_IntegerType(3), nullable=False, server_default="'1'")
    area = Column(_StringType(20), nullable=False)
    goods_label = Column(_StringType(300), server_default="''")
    order_detail_info_json = Column(_StringType(2000), nullable=False, server_default="''")
    category_id_path = Column(_StringType(255), nullable=False, server_default="''")
    category_cn_name_path = Column(_StringType(255), nullable=False, server_default="''")
    platform_category_id = Column(_StringType(255), nullable=False, server_default="''")
    cost_price = Column(DECIMAL(15, 4), nullable=False, server_default="'0.0000'")


class OdsPckHaikwanDetail(Base):
    __tablename__ = 'ods_pck_haikwan_detail'

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    sku = Column(_StringType(50), nullable=False, index=True, server_default="''")
    cn_name = Column(_StringType(200), nullable=False, server_default="''")
    en_name = Column(_StringType(200), nullable=False, server_default="''")
    quantity = Column(_IntegerType(11), nullable=False)
    producing_area = Column(_StringType(10))
    weight = Column(DECIMAL(9, 3), nullable=False, server_default="'0.000'")
    currency = Column(_StringType(10))
    value = Column(DECIMAL(10, 3), nullable=False, server_default="'0.000'")
    hscode = Column(_StringType(20))
    create_date = Column(DateTime, nullable=False, index=True)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default="'1970-01-02 00:00:00'")
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")


class OdsPckInfo(Base):
    __tablename__ = 'ods_pck_info'
    __table_args__ = (
        Index('idx_process_center_id', 'process_center_id', 'in_ods_date_time', 'pck_state'),
    )

    id = Column(_IntegerType(20), primary_key=True)
    package_id = Column(_StringType(20), nullable=False, index=True)
    order_id = Column(_StringType(30), nullable=False, index=True, server_default="''")
    batchgridorderdata_id = Column(_StringType(30), nullable=False, server_default="''")
    process_center_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delivery_type = Column(_StringType(50), nullable=False, server_default="''")
    order_type = Column(_StringType(20))
    detail_type = Column(_IntegerType(11))
    package_type = Column(_IntegerType(11))
    batch_processing_id = Column(_StringType(50), index=True)
    pck_state = Column(_IntegerType(11), index=True)
    change_state_time = Column(DateTime)
    in_ods_date_time = Column(DateTime, nullable=False, server_default='CURRENT_TIMESTAMP')
    in_wsp_datetime = Column(DateTime)
    in_system_datetime = Column(DateTime)
    freight = Column(DECIMAL(18, 3))
    total_price = Column(DECIMAL(18, 3))
    actual_weight = Column(DECIMAL(9, 3))
    goods_pck_weight = Column(DECIMAL(9, 3), server_default="'0.000'")
    volume_weight = Column(DECIMAL(9, 3), server_default="'0.000'")
    package_length = Column(DECIMAL(9, 2), server_default="'0.00'")
    package_width = Column(DECIMAL(9, 2), server_default="'0.00'")
    package_height = Column(DECIMAL(9, 2), server_default="'0.00'")
    post_id = Column(_StringType(11), index=True)
    post_type_options = Column(_StringType(1000))
    online_psot_type = Column(_StringType(100))
    trace_id = Column(_StringType(80), index=True)
    way_bill_no = Column(_StringType(80), nullable=False, index=True, server_default="''")
    delivery_date = Column(DateTime, index=True)
    delivery_user_id = Column(_IntegerType(11))
    delivery_user = Column(_StringType(20), index=True)
    receive_name = Column(_StringType(100))
    phone = Column(_StringType(50))
    country_id = Column(_StringType(20), index=True)
    country = Column(_StringType(300))
    county = Column(_StringType(300))
    city = Column(_StringType(300))
    buyer_address1 = Column(_StringType(300))
    buyer_address2 = Column(_StringType(300))
    zip = Column(_StringType(150))
    belonging = Column(_StringType(20))
    belonging_id = Column(_IntegerType(2), nullable=False, server_default="'0'")
    pck_remarks = Column(_StringType(800))
    platform_order_id = Column(_StringType(50))
    master_post_no_jump = Column(_IntegerType(1))
    is_part_delivery = Column(BIT(1))
    is_gift_lack_delivery = Column(BIT(1))
    processing_scheme = Column(_StringType(50))
    processing_scheme_remark = Column(_StringType(1000))
    return_reason_name = Column(_StringType(100))
    return_reason_remark = Column(_StringType(1000))
    create_date = Column(DateTime, nullable=False, index=True)
    create_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    create_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_date = Column(DateTime)
    modify_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    modify_user_name = Column(_StringType(50), nullable=False, server_default="''")
    is_deleted = Column(BIT(1), nullable=False)
    delete_date = Column(DateTime)
    delete_user_id = Column(_IntegerType(11), nullable=False, server_default="'0'")
    delete_user_name = Column(_StringType(50), nullable=False, server_default="''")
    modify_time_stamp = Column(DateTime, nullable=False, index=True, server_default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')
    lock_version = Column(_IntegerType(20), nullable=False, server_default="'0'")
    ods_site_server = Column(_StringType(50))
    init_pck_volume = Column(DECIMAL(20, 3), nullable=False, server_default="'0.000'")
    address = Column(_StringType(300), nullable=False, server_default="''")
    email = Column(_StringType(150), nullable=False, server_default="''")
    in_ods_date_new = Column(DateTime, nullable=False, server_default='CURRENT_TIMESTAMP')
    real_post_id = Column(_StringType(20), nullable=False, server_default="''")
    payment_type = Column(_IntegerType(4), nullable=False, server_default="'1'")
    user_trace_id = Column(_StringType(255), nullable=False, server_default="''")
    cabinet_number = Column(_StringType(50), nullable=False, server_default="''")
    earliest_delivery_date = Column(DateTime, nullable=False, server_default="'1970-01-01 00:00:00'")
    is_list_scan = Column(_IntegerType(1), nullable=False, server_default="'0'")
    deliver_goods_id = Column(_StringType(30), nullable=False, server_default="''")
    order_info_json = Column(_StringType(2000), nullable=False, server_default="''")
    send_date = Column(DateTime)
